### PR TITLE
Added Home Page

### PR DESCRIPTION
**Pull request by mohakvni**
### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Added Home Page

### Testing
How did you confirm your changes worked? 
Screen Shot 2022-04-14 at 6 06 21 PM

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

### CODE REVIEW

**Comment by PatrickBrown1** [comment]
^ Also made changes to route to homepage from "/"

**Review by JamesZhang878 — APPROVED** [review]
lgtm!

**Comment by PatrickBrown1** [comment]
Looks good to me up to this point. Will approve and merge when we integrate further with wish wednesday backend.

**Review by JamesZhang878 — APPROVED** [review]
lgtm!

**Review by PatrickBrown1 — APPROVED** [review]

**Pull request merged**
