### PR TITLE
V1 Push to Master

### PR DESCRIPTION
**Pull request by PatrickBrown1**
# Version 1 Push to Master
### Changes
What changes did you make?
- User accounts, profile pages, profile picture uploads, change password, delete account
- User management for admins, list users
- File and category management - upload files, delete files, edit files, create categories, edit categories, delete categories, download files

### CODE REVIEW

**Review by JamesZhang878 — CHANGES_REQUESTED** [review]
**Wish Granting Page**
- The background pictures don't change between the different tabs. I vaguely remember seeing different background pictures for the different tabs in the Wish Granting Page. I'm assuming that this is something that would be implemented in V2?

**Profile Page**
- When I upload a profile picture, the edit button disappears, and I need to refresh the page if I wanted to edit the picture that I just uploaded. I'm not sure if this was intentional.
- I'm able to change my password into the same password as my current password. I'm not sure if we want to prevent users from having their new password match their current password.

**Login Process**
- This was brought up in the meeting, but I'll just make a note of it here as a reminder. But, users who haven't been approved yet are able to sign in.

Other than that, LGTM!

**Review by aksharans — CHANGES_REQUESTED** [review]
- in mobile view, a small part of the volunteers table/search bar is cut off in the 2nd breakpoint from 850px to 795px 
- i think this was already mentioned but just to put it here as well, when clicking the allow access button, the modal first appears in the bottom then moves to the middle
- saw a small issue with the mobile searchbar onblur, where typing some input then pressing the searchbar would close the searchbar, I believe the fix is just adding:
`input === ""` in the if statement on line 89 of Search.js
- i'm also seeing an issue with the search mobile/desktop integration (switching from mobile to desktop and vice versa doesn't maintain the states of the input and creates duplicate modals), which I think may have somehow gotten mixed up in some of the merges?

**Comment by Cubified** [comment]
A few more things I've noticed:
 - The "User [name] has been given access" modal is too large on mobile, we should set a `max-width` or similar
 - Mobile scrolling on the wish granting page is a big wonky — the body itself scrolls, but so does the `<WishStep />` tag.  I think the most recent commit to my PR caused this (since I definitely would've noticed it before), but I'll investigate
 - Shouldn't the button that says "Admin" say "Admins" if the button right next to it says "Volunteers"?  The designs had it as "Admin" so I'm not sure

**Review by JamesZhang878 — APPROVED** [review]

**Comment by mohakvni** [comment]
In the mobile version, when you search a file and try and delete/edit it, the "confirm delete/edit" pop up doesn't come up until you close the search window!https://user-images.githubusercontent.com/68292499/161451365-557e8622-cd96-442c-ae0a-7792fe057df0.MOV

**Review by aksharans — APPROVED** [review]

**Comment by PatrickBrown1** [comment]
> In the mobile version, when you search a file and try and delete/edit it, the "confirm delete/edit" pop up doesn't come up until you close the search window!https://user-images.githubusercontent.com/68292499/161451365-557e8622-cd96-442c-ae0a-7792fe057df0.MOV

fixed

**Comment by PatrickBrown1** [comment]
> * Shouldn't the manage page tab that says "Admin" say "Admins" if the tab right next to it says "Volunteers"?  The designs had it as "Admin" so I'm not sure

fixed

**Review by mohakvni — APPROVED** [review]

**Comment by Cubified** [comment]
> Mobile scrolling on the wish granting page is a big wonky — the body itself scrolls, but so does the <WishStep /> tag. I think the most recent commit to my PR caused this (since I definitely would've noticed it before), but I'll investigate

Fixed

**Review by Cubified — APPROVED** [review]
Nice work everyone!

**Pull request merged**
