### PR TITLE
Feature/cubified/profile pictures

### PR DESCRIPTION
**Pull request by Cubified**
### Administrative Info
[GitHub Issue N/A]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added a UI for uploading and viewing users' profile pictures
   - Modal with cropping and error messages
- Added backend routes for uploading and viewing profile pictures
   - Uses `sharp`/`libvips` to crop, resize, compress, and convert images for storage on S3
   - Validates uploads before processing to ensure an image of less than 16MB has been uploaded
- Other:
   - Changed file routes to use `multer-s3` so users' files are never stored on server's disk
   - Switched to using signed cookies for token storage instead of `localStorage/sessionStorage` (accessing profile pictures via `` tag would have been very clunky otherwise -- this can now also apply to viewing files in the wish granting tab)

### Testing
How did you confirm your changes worked? 
- Manual testing, should do more intensive/comprehensive pentesting of anything related to file uploads

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

https://user-images.githubusercontent.com/8538846/156076131-c9968846-7c13-495c-b23c-3bd945105c08.mov

### CODE REVIEW

**Review by PatrickBrown1 — CHANGES_REQUESTED** [review]
All works really well! One small thing is that the profile doesn't update when a new one is uploaded, you have to reload the page for the change to take affect. 

We could reload the page, but that would be a little clunky.

We could also have some sort of variable in img src url that updates whenever you upload a new pfp. If we make a context for this, we could pass this into the navbar and the profile page and increment it (or randomize it) whenever a new pfp is uploaded, triggering a rerender for the img tag.

**Review by PatrickBrown1 — CHANGES_REQUESTED** [review]
Found a couple more bugs:

1. Logging in and out between users leads to issues with the cached pfps. I uploaded a pfp for one user, logged out and into another user, and the navbar pfp was the first user's pfp, while the profile page's pfp is the current user's pfp. Reloading fixes this. Maybe clearing the current user's pfps from cache when a log out occurs would help (i.e. http://localhost:3000/user/pfp/?cacheBreaker=0)?
2. Profile page is rendering the current user's pfp even if it's not the current user's page. I think we need to change the img tag's src to 
```src={`${API_ENDPOINTS.PFP_GET}/${id ?? "" }?cacheBreaker=${cacheBreaker}`}```
4. The manage tab doesn't appear in the navbar on the profile page, even if the user is an admin
5. The image upload button appears on all profile pages, not just the current user (super simple fix, just add { isCurrentUser && <button>...)

**Comment by PatrickBrown1** [comment]
> 3. The manage tab doesn't appear in the navbar on the profile page, even if the user is an admin
Fixed by making this change 
image

**Review by aksharans — COMMENTED** [review]
PFP LGTM! 
Last minor thing I saw was that the modal wasn't popping up when creating new account, for the different res for the login and signup (in LoginPage.js), so I think this fixes it?
`const success = Boolean(res && !res.error && (isLogin ? res.user : true));`

**Review by PatrickBrown1 — APPROVED** [review]

**Review by aksharans — APPROVED** [review]
LGTM

**Pull request merged**
